### ISSUE TITLE
Read and write to dcc.Store objects from non-clicked tabs

### ISSUE THREAD

**Issue by lufire** [ZBT-Tools/PEMFC-Model#28]
Wouldn't a combination of the two examples in [this ](https://dash.plotly.com/dash-core-components/store) tutorial solve the discussed problem? The first example includes input to the dcc.Store based on a timestamp instead of a click ? (Input(store, 'modified_timestamp')) and possibly some techniques in the second example "Share data between callbacks" ...

**Comment by lufire** [comment]
this is the explanation in the tutorial I thought might help, but maybe I didn't fully understand the problem yet:

"Retrieving the initial store data

If you use the data prop as an output, you cannot get the initial data on load with the data prop. To counter this, you can use the modified_timestamp as Input and the data as State."

**Comment by kamalizzu** [comment]
The issue has been resolved. The main problem was the way the _tab_layout_ of each tab was called through **def switch_tab** callback inside the app.layout which makes the ids from tabs other than chosen tab inaccessible/undetectable, hence error arises due to the program not finding specified input ids. I have modified the way the layout is structured so that ids from different tabs would be accessible on the dot. More about the issue can be found under this [discussion](https://stackoverflow.com/questions/67407571/handling-dash-callback-of-an-input-inside-the-multi-tab-app)

**Comment by ZBT-Tools** [comment]
thank you! 
however i'll leave it open until you close it in connection with the respective commit

**Comment by lufire** [comment]
has been resolved

**Comment by lufire** [comment]
has been resolved
