### ISSUE TITLE
'Load Settings' is not working

### ISSUE THREAD

**Issue by fkuschel** [ZBT-Tools/PEMFC-Model#29]
Hi @kamalizzu, @lufire ,

loading a settings .json-file seems not to work for me. 

Below a step-by-step of what I did, maybe you can try it on your side:

1. Start Dash app from PyCharm (Model is running!)
2. Save settings as "settings_Config1.json" at Desktop.
3. Modify number of cells :
    ![image](https://user-images.githubusercontent.com/94350939/149517255-6b7b8132-314c-416d-bf2e-edcc98bb436e.png)
4. Save settings as "settings_Config2.json" at Desktop. (No. of cells is saved correctly in new settings file)
5. Load "settings_Config1.json" from Desktop. Nothing happens. 
6. PyCharm prints error: 
![image](https://user-images.githubusercontent.com/94350939/149517708-fbd05ef2-778a-4731-bdf8-9e0244f85e0b.png)

**Comment by kamalizzu** [comment]
Thank you for pointing it out. The issue has just been solved. It is due to the logical problem when processing multiple inputs under def multi_inputs() in dash_functions.py. Input components in the Dash app that holds multiple value would have multiple components that would hold the multiple values. This would be first initialised and its component ID would be denoted by adding '_' followed by the numbering the values depending of how many value that that component should have. 

The 'if else' conditions from before did not take into account the component ID that has no multiple inputs but has similar naming convention as the initialised multiple input components (IDs with '_' on the 2nd last of the string). This has now been changed into 

> if k[-1:].isnumeric() is False

from

> if k[-2:-1] != '_':

Other than that, some of the sim_name component retrieved from GUI app was not implemented in the Dash app (such as [output, directory] ). This is solved by using the try statement in handling exception inside the def  parse_contents() in dash_functions.py when parsing the value from setting.json that do not include the [output, directory] (from saving settings through Dash).

**Comment by fkuschel** [comment]
Thanks for your fast response @kamalizzu, but I have to reopen the issue.

Something seems still wrong! 

I can read in values from a setting file now, but afterwards I can not run the simulation anymore.

Please check if you can reproduce the error:

1. Start dash server
2. Press run
3. Save (initial) settings to a setting file. 
4. Load this (unmodified) setting file.
5. Run again --> Error!

![image](https://user-images.githubusercontent.com/94350939/149564441-f4722676-d6fb-4708-941c-2e3e81e6a758.png)

**Comment by lufire** [comment]
Hi @kamalizzu, @fkuschel,
fixed the errors in dash_run.py (def upload_settings):

`
...
          id_match = set.union(set(list_ids),
                                 set([item[:-2] for item in list_ids2]))


            for k, v in j_file.items():
                if k in id_match:
                    if isinstance(v, list):
...
`
